package org.pmcsn.model;

public enum EventType {
    ARRIVAL_LUGGAGE_CHECK,
    LUGGAGE_CHECK_DONE,
    ARRIVAL_CHECK_IN,
    CHECK_IN_DONE,
    ARRIVAL_BOARDING_PASS_SCANNERS,
    BOARDING_PASS_SCANNERS_DONE,
    ARRIVAL_SECURITY_CHECK,
    SECURITY_CHECK_DONE,
    ARRIVAL_PASSPORT_CHECK,
    PASSPORT_CHECK_DONE,
    ARRIVAL_STAMP_CHECK,
    STAMP_CHECK_DONE,
    ARRIVAL_BOARDING,
    BOARDING_DONE
}
