package org.pmcsn.model;

public enum EventType {
    ARRIVAL_LUGGAGE_CHECK,
    LUGGAGE_CHECK_DONE,
    ARRIVAL_CHECK_IN_TARGET,
    CHECK_IN_TARGET_DONE,
    ARRIVAL_CHECK_IN_OTHERS,
    CHECK_IN_OTHERS_DONE,
    ARRIVAL_BOARDING_PASS_SCANNERS,
    BOARDING_PASS_SCANNERS_DONE,
    ARRIVAL_SECURITY_CHECK,
    SECURITY_CHECK_DONE,
    ARRIVAL_PASSPORT_CHECK,
    PASSPORT_CHECK_DONE,
    ARRIVAL_STAMP_CHECK,
    STAMP_CHECK_DONE,
    ARRIVAL_BOARDING_TARGET,
    BOARDING_TARGET_DONE,
    ARRIVAL_BOARDING_OTHERS,
    BOARDING_OTHERS_DONE
}
